name: shell2http
version: '1.14.2'
summary: Executing shell commands via HTTP server
description: |
  HTTP-server for executing shell commands. Designed for develop, prototype or remote control.
  Settings through two command line arguments, path and shell command.
  By default bind to :8080.
  https://github.com/msoap/shell2http
grade: stable
confinement: strict
base: core18
parts:
  shell2http:
    plugin: go
    go-importpath: github.com/msoap/shell2http
    source: .
    source-type: git

apps:
  shell2http:
    command: bin/shell2http
    plugs: [network-bind, network, home]
